sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t etiennewl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true etiennewl/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-831850936933"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY