sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t etiennewl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true etiennewl/docker-react npm run test